# Generated by Django 5.0.3 on 2026-04-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='start_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
