# Generated by Django 5.0.3 on 2026-06-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_userprofile_start_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test_completed',
            field=models.BooleanField(default=False),
        ),
    ]
